vp0:
    image: hyperledger/fabric-peer
    ports:
    - 5000:5000
    - 30000:30303
    environment:
    - CORE_PEER_ID=vp0
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=http://172.17.0.1:2375
    - CORE_LOGGING_LEVEL=DEBUG
    command: peer node start
vp1:
    extends:
        service: vp0
    ports:
    - 5001:5000
    - 30001:30303
    environment:
      - CORE_PEER_ID=vp1
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
    links:
      - vp0
vp2:
    extends:
        service: vp0
    ports:
    - 5002:5000
    - 30002:30303
    environment:
      - CORE_PEER_ID=vp2
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
    links:
      - vp0
vp3:
    extends:
        service: vp0
    ports:
    - 5003:5000
    - 30003:30303
    environment:
      - CORE_PEER_ID=vp3
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
    links:
      - vp0
